image:
  file: .gitpod.Dockerfile
tasks:
  - init: >
      mkdir -p /home/gitpod/.config/nix &&
      echo 'sandbox = false' >> /home/gitpod/.config/nix/nix.conf
  - name: nix
    command: |
      direnv allow
vscode:
  extensions:
    - bbenoist.Nixs